### ISSUE TITLE
networking_protocol: suggestions for improvement

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/kinode-book#34]
https://github.com/uqbar-dao/uqbar-book/blob/e8a3d989d94a3e41ea87f25a621c11e890fc00e7/src/networking_protocol.md?plain=1#L38-L41

Is this up to date? Does it need a `.uq`/`.no` tld?

---

https://github.com/uqbar-dao/uqbar-book/blob/e8a3d989d94a3e41ea87f25a621c11e890fc00e7/src/networking_protocol.md?plain=1#L45

More information about private nodes would be useful. Here they are mentioned, and public/non-public is mentioned here: 

https://github.com/uqbar-dao/uqbar-book/blob/e8a3d989d94a3e41ea87f25a621c11e890fc00e7/src/networking_protocol.md?plain=1#L66-L68

in a way that sounds different, namely, like direct/indirect. Recommend explicitly discussing what a private node is and how it works: how does router know how to talk to it, etc.

---

https://github.com/uqbar-dao/uqbar-book/blob/e8a3d989d94a3e41ea87f25a621c11e890fc00e7/src/networking_protocol.md?plain=1#L69

Either need to have the Error here or link to it.

**Comment by dr-frmr** [comment]
Yes, I'll close now
