### ISSUE TITLE
vfs: define drive

### ISSUE THREAD

**Issue by hosted-fornet** [uqbar-dao/kinode-book#67]
We need a conceptual discussion of VFS drives and how capabilities work in the system. It'd be natural to have this discussion in either https://github.com/uqbar-dao/kinode-book/blob/main/src/files.md or https://github.com/uqbar-dao/kinode-book/blob/main/src/apis/vfs.md

**Comment by bitful-pannul** [comment]
https://github.com/uqbar-dao/kinode-book/pull/71
